import Head from "next/head";
import useAppStore from "@/store/app";
import usePromise from "@/hooks/usePromise";

export default function Home() {
  const { fetchMock } = useAppStore();
  const [mockData] = usePromise(fetchMock, [fetchMock]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App">
          <img
            className="mainPic"
            width="150"
            height="150"
            src="https://via.placeholder.com/150"
            alt="Placeholder"
          />
          <div className="mainContent">
            <h1>title</h1>
            <p className="address">address</p>
            <button>See description</button>
            <p className="description">description</p>
          </div>
        </div>
      </main>
    </>
  );
}
