import Head from "next/head";
import useAppStore from "@/store/app";
import usePromise from "@/hooks/usePromise";
import FeatureCard from "@/components/FeatureCard";

export default function Home() {
  const { fetchMock } = useAppStore();
  const [mockData] = usePromise(fetchMock, [fetchMock]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FeatureCard {...mockData!} />
      </main>
    </>
  );
}
